# Stage 1: Build
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

ENV NEXT_PRIVATE_STANDALONE=true
#env
ARG NODE_ENV=${NODE_ENV}
ENV NODE_ENV=${NODE_ENV}
ARG DB_HOST=${DB_HOST}
ENV DB_HOST=${DB_HOST}
ARG DB_USER=${DB_USER}
ENV DB_USER=${DB_USER}
ARG DB_PORT=${DB_PORT}
ENV DB_PORT=${DB_PORT}
ARG DB_PASS=${DB_PASS}
ENV DB_PASS=${DB_PASS}
ARG DB_DATABASE=${DB_DATABASE}
ENV DB_DATABASE=${DB_DATABASE}
ARG DB_CONECTION_LIMIT=${DB_CONECTION_LIMIT}
ENV DB_CONECTION_LIMIT=${DB_CONECTION_LIMIT}
ARG DATABASE_URL=${DATABASE_URL}
ENV DATABASE_URL=${DATABASE_URL}
ARG NEXT_PUBLIC_PACKS_URL_S3=${NEXT_PUBLIC_PACKS_URL_S3}
ENV NEXT_PUBLIC_PACKS_URL_S3=${NEXT_PUBLIC_PACKS_URL_S3}
ARG NEXT_PUBLIC_STATIC_URL_S3=${NEXT_PUBLIC_STATIC_URL_S3}
ENV NEXT_PUBLIC_STATIC_URL_S3=${NEXT_PUBLIC_STATIC_URL_S3}
ARG PATH_LOGS=${PATH_LOGS}
ENV PATH_LOGS=${PATH_LOGS}
ARG URL_BASE=${URL_BASE}
ENV URL_BASE=${URL_BASE}
ARG IMAGE_USER_PREVIEW=${IMAGE_USER_PREVIEW}
ENV IMAGE_USER_PREVIEW=${IMAGE_USER_PREVIEW}
ARG TZ=${TZ}
ENV TZ=${TZ}
ARG JWT_SECRET=${JWT_SECRET}
ENV JWT_SECRET=${JWT_SECRET}
ARG JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
ENV JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
ARG AUTH_JWT_EXPIRES_IN=${AUTH_JWT_EXPIRES_IN}
ENV AUTH_JWT_EXPIRES_IN=${AUTH_JWT_EXPIRES_IN}
ARG REFRESH_JWT_EXPIRES_IN=${REFRESH_JWT_EXPIRES_IN}
ENV REFRESH_JWT_EXPIRES_IN=${REFRESH_JWT_EXPIRES_IN}
ARG AUTH_COOKIES_EXPIRES_IN=${AUTH_COOKIES_EXPIRES_IN}
ENV AUTH_COOKIES_EXPIRES_IN=${AUTH_COOKIES_EXPIRES_IN}
ARG REFRESH_COOKIES_EXPIRES_IN=${REFRESH_COOKIES_EXPIRES_IN}
ENV REFRESH_COOKIES_EXPIRES_IN=${REFRESH_COOKIES_EXPIRES_IN}
ARG VERIFIED_COOKIES_EXPIRES_IN=${VERIFIED_COOKIES_EXPIRES_IN}
ENV VERIFIED_COOKIES_EXPIRES_IN=${VERIFIED_COOKIES_EXPIRES_IN}
ARG AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ARG AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ARG AWS_ENPOINT=${AWS_ENPOINT}
ENV AWS_ENPOINT=${AWS_ENPOINT}
ARG AWS_REGION=${AWS_REGION}
ENV AWS_REGION=${AWS_REGION}
ARG AWS_BUCKET_STATIC=${AWS_BUCKET_STATIC}
ENV AWS_BUCKET_STATIC=${AWS_BUCKET_STATIC}
ARG AWS_BUCKET_PACKS=${AWS_BUCKET_PACKS}
ENV AWS_BUCKET_PACKS=${AWS_BUCKET_PACKS}
ARG NEXT_PUBLIC_API_CLIENT_ID=${NEXT_PUBLIC_API_CLIENT_ID}
ENV NEXT_PUBLIC_API_CLIENT_ID=${NEXT_PUBLIC_API_CLIENT_ID}
ARG API_SECRET_KEY=${API_SECRET_KEY}
ENV API_SECRET_KEY=${API_SECRET_KEY}
ARG API_PAYPAL=${API_PAYPAL}
ENV API_PAYPAL=${API_PAYPAL}
ARG API_SECRET_KEY=${API_SECRET_KEY}
ENV HOST=${HOST}

# Generate Prisma Client
RUN npx prisma generate

RUN npm run build

# Stage 2: Run
FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV production

# Copy everything needed for 'npm start'
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 80
ENV PORT 80

# Next.js 16 requires 'npm start' for this configuration
CMD ["npm", "start"]