import { notFound } from 'next/navigation';
import { Locale, hasLocale, NextIntlClientProvider } from 'next-intl';
import { getTranslations, setRequestLocale } from 'next-intl/server';
import { Inter } from 'next/font/google';
import "../globals.css";
import Header from '../layout/components/header';
import { routing } from '@/src/i18n/routing';
import logger, { jsonLog } from '../utils/logger';


const inter = Inter({ subsets: ['latin'] });

export function generateStaticParams() {
    return routing.locales.map((locale) => ({ locale }));
}

export async function generateMetadata(
    props: Omit<LayoutProps<'/[locale]'>, 'children'>
) {
    const { locale } = await props.params;

    const t = await getTranslations({
        locale: locale as Locale,
        namespace: 'LocaleLayout'
    });

    return {
        title:/*  t('title') */'',
        description: "Generated by create next app",
    };
}

export default async function LocaleLayout({
    children,
    params
}: LayoutProps<'/[locale]'>) {
    // Ensure that the incoming `locale` is valid
    const { locale } = await params;
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }
    logger.info(`env LocaleLayout ${jsonLog({
        host: process.env.DB_HOST,
        port: parseInt(process.env.DB_PORT!),
        connectionLimit: parseInt(process.env.DB_CONECTION_LIMIT!),
        user: process.env.DB_USER,
        password: process.env.DB_PASS,
        database: process.env.DB_DATABASE,
    })}`)
    // Enable static rendering
    setRequestLocale(locale);

    return (
        <html className=" text-white" lang={locale}>
            <body className={`${inter.className} bg-neutral-900`}>
                <NextIntlClientProvider>
                    <Header></Header>
                    <div className='h-full'>
                        <div className="px-2 py-2 md:px-10 lg:px-20 xl:px-64 2xl:px-72 md:py-5 lg:py-10 xl:py-14">
                            {children}
                        </div>
                    </div>
                    <div className='bg-slate-950 p-2'></div>
                </NextIntlClientProvider>
            </body>
        </html>

    );
}