import { notFound } from 'next/navigation';
import { Locale, hasLocale, NextIntlClientProvider } from 'next-intl';
import { getTranslations, setRequestLocale } from 'next-intl/server';
import { Inter } from 'next/font/google';
import "../globals.css";
import Header from '../layout/components/navigate/header';
import { routing } from '@/src/i18n/routing';
import { AuthProvider } from '@/src/providers/AuthProvider';
import AxiosInterceptorProvider from '@/src/providers/AxiosInterceptorProvider';
import { Suspense } from 'react';
import { Splashscreen } from '../layout/components/splashcreen/splashscreen';
import ToastProvider from '@/src/providers/toastProvider';
import AlertProvider from '@/src/providers/alertProvider';
import { getCurrentUser } from '../utils/auth';
//import logger, { jsonLog } from '../utils/logger';

export interface PageHomeProps {
    params: Promise<{
        locale: string
    }>
}

const inter = Inter({ subsets: ['latin'] });

export function generateStaticParams() {
    return routing.locales.map((locale) => ({ locale }));
}

export async function generateMetadata(
    props: Omit<LayoutProps<'/[locale]'>, 'children'>
) {
    const { locale } = await props.params;

    const t = await getTranslations({
        locale: locale as Locale,
        namespace: 'LocaleLayout'
    });

    return {
        title:/*  t('title') */'',
        description: "Generated by create next app",
    };
}

export default async function LocaleLayout({
    children,
    params
}: LayoutProps<'/[locale]'>) {
    // Ensure that the incoming `locale` is valid
    const { locale } = await params;
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }
    // Enable static rendering
    setRequestLocale(locale);
    const user = await getCurrentUser();
    
    return (
        <html className=" text-white" lang={locale}>
            <body className={`${inter.className} bg-neutral-900`}>
                <Suspense fallback={<Splashscreen></Splashscreen>}>
                    <NextIntlClientProvider>
                        <AuthProvider auth={user === null ? user : {
                            email: user!.email,
                            name: user!.name,
                            nick: user!.nick,
                            image: `${process.env.NEXT_PUBLIC_STATIC_URL_S3}/img/${user!.image}`,
                        }}>
                            <AxiosInterceptorProvider>
                                <AlertProvider>
                                    <Header></Header>
                                    <ToastProvider>
                                        <div className='h-full'>
                                            {children}
                                        </div>
                                        <div className='bg-neutral-800 p-2'>
                                            Footer 2026
                                        </div>
                                    </ToastProvider>
                                </AlertProvider>
                            </AxiosInterceptorProvider>
                        </AuthProvider>
                    </NextIntlClientProvider>
                </Suspense>
            </body>
        </html >

    );
}