
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import "../globals.css";
import Header from "../layout/components/header";

config.autoAddCss = false;
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface LayoutProps {
    children: React.ReactNode
    params: Promise<{ locale: string }>
}
export default async function Layout({
    children,
    params,
}: LayoutProps) {
    //console.log(locale)
    //logger.info(`Init Web`);
    const { locale } = await params;
    //const messages = await getMessages();
    return (
        <html lang={locale} className="text-white">
            {/* <NextIntlClientProvider messages={messages}> */}

                <body className={`${inter.className} `}>
                    <Header></Header>
                    <div className="bg-neutral-900 px-2 py-2 md:px-10 lg:px-20 xl:px-52 md:py-5 lg:py-10 xl:py-10">
                        {children}
                    </div>

                    <div>footer</div>
                </body>
            {/* </NextIntlClientProvider> */}
        </html>
    );
}
